# References:
# https://some-natalie.dev/blog/kaniko-in-arc/
# https://dev.to/ipo/using-kaniko-to-build-and-publish-container-image-with-github-action-on-github-self-hosted-runners-d5m

name: Image Build
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: arc-runner-${{ github.event.repository.name }}
    container:
      image: gcr.io/kaniko-project/executor:debug
    permissions:
      contents: read
      packages: write
    steps:
    - name: Build and release container
      run: |
        cat > /kaniko/.docker/config.json <<EOF
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64 -w0)"
            }
          }
        }
        EOF

        /kaniko/executor \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="ghcr.io/${{ github.repository }}:${{ github.head_ref || github.ref_name }}" \
          --push-retry 3